### ISSUE TITLE
How it works for 2D?

### ISSUE THREAD

**Issue by paulocoutinhox** [henriquelalves/GodotCharacterInputController#2]
Hi,

How it works for 2D?

I read your source for 3D, but don't understand how i can detect x/y movement to my player do left/right and jump.

Can you help me with a simple code here?

Thanks.

**Comment by Hansel-Dsilva** [comment]
Exactly! The plugin creator has not even taken the effort to document HOW TO USE the damn thing

**Comment by henriquelalves** [comment]
@prsolucoes Hi! Sorry taking so long to answer. I actually made this addon thinking only in a 3D solution for movement + camera, so haven't thought on making other kinds of examples. It should be pretty straightforward tho; you'd only need to add an overlay on top of the addon with the 2D buttons you want to detect (e.g. a Control node below the Addon node with the buttons you want to detect). When I get time I'll try updating it.

@Hansel-Dsilva This is an open-source solution I provided for free with no warranties whatsoever. If you don't want to use it because it lacks documentation, it's fine by me, but your comment is pretty much you feeling entitled of something you don't have, so my recommendation for you is to be more polite next time, or else you risk simply being ignored by any sane developer.

EDIT: I'm going to add a TO-DO list on the README and leave this issue open for now. I can't guarantee when I'll be able to add any kind of example or documentation to the addon, but I'll update this Issue when possible.

**Comment by Hansel-Dsilva** [comment]
Ok sorry, my bad. So how does one go about utilizing your plugin?

**Comment by henriquelalves** [comment]
@Hansel-Dsilva Np. The plugin only does one thing, that is to get a user input and give back some 'interpreted' values (e.g. how far and in which direction the left analog stick is moving) based on the two halves of the device screen. The project example is just like that: it reads on the plugin Node what are the values for the left analog stick (left half of the screen) to move the character and the values of each swipe on the right half of the screen to move the camera. It's basically up to you how to interpret those values, but it is hopefully straightforward if you adapt the project this addon comes with to your necessities.

I'm currently stacked with work and other projects I need to finish, but I'll try creating a simple 2D example by the end of today (GMT-3, mind you).

**Comment by henriquelalves** [comment]
@Hansel-Dsilva @prsolucoes I just created a branch called "2d_example" with a fully functional but ugly 2D example. The idea is to use the left analog stick do control the character, and use the button on the right side to shoot a projectile. It's worth noting that, when using this plugin, you can't use 'normal' buttons; that's an unfortunate limitation caused by how Godot emulates clicks on touch-based devices: when emulating mouse-clicks, Godot won't be able to get multitouch gestures (which is the core of this addon). Since this option is disabled, you'd have to create your own kind of button getting a "gui_input" event, or using Godot's TouchScreenButton.
